# Generated by Django 5.1.2 on 2024-10-13 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_analyzer_app', '0002_audio_promptassociation_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptassociation',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompt_associations', to='audio_analyzer_app.audio'),
        ),
    ]
